Quickstart - Migrated quickstarts  to ES6 features, modified let and const keywords instead of using var
googleworkspace/apps-script-samples pull request #260
Opened 2022-01-12 16:24 UTC by RajeshGogo

# Description

Migrated quickstarts  to ES6 features, modified let and const keywords instead of using var, added try-catch block to handle the exception added comments

Fixes # 214188556, 211109344, 214185422, 211081627, 214236683, 211551535, 214237374, 214186022, 214185411 & 214186745

## Is it been tested?
- [X] Development testing done

## Checklist

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have performed a peer-reviewed with team member(s)
- [X] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [X] Any dependent changes have been merged and published in downstream modules

2022-01-13 17:25 UTC, sqrrrl requested changes
A few minor things, otherwise looks good :)

2022-01-13 17:25 UTC, sqrrrl commented on classroom/quickstart/quickstart.gs
> +    if (courses && courses.length === 0) {
Need to fix logic when changing to guard clause (otherwise if courses is null/undefined it will fail)

```
if (!courses || courses.length === 0) {
 ...
}
```

2022-01-13 17:25 UTC, sqrrrl commented on calendar/quickstart/quickstart.gs
> +    if (events.length===0) {
Minor nit -- add spaces around `===`'

2022-01-13 17:25 UTC, sqrrrl commented on tasks/quickstart/quickstart.gs
> +    if (taskLists && taskLists.length === 0) {
Fix logic:

```
if (!tasksLists || taskLists.length === 0) {
  ...
}
```

2022-01-13 17:25 UTC, sqrrrl commented on drive/activity-v2/quickstart.gs
> +    if (activities && activities.length === 0) {
Fix logic:

```
if (!activities || activities.length === 0) {
 ...
}
```

2022-01-14 15:50 UTC, RajeshGogo commented on classroom/quickstart/quickstart.gs
> +    if (courses && courses.length === 0) {
Fixed in PR 262

2022-01-14 15:50 UTC, RajeshGogo commented on tasks/quickstart/quickstart.gs
> +    if (taskLists && taskLists.length === 0) {
Fixed in PR 262

2022-01-14 15:51 UTC, RajeshGogo commented on drive/activity-v2/quickstart.gs
> +    if (activities && activities.length === 0) {
Fixed in PR 262

2022-01-18 18:54 UTC, merged