Add files via upload
googleworkspace/apps-script-samples pull request #425
Opened 2023-10-26 19:22 UTC by danielatgoogle

Hello DevRel friends!

# Description

Working with @gtondello, I'm uploading code samples for the Google Chat Advanced Service in Apps Script launch.

Fixes # (issue)

## Is it been tested?
- [X] Development testing done

## Checklist

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have performed a peer-reviewed with team member(s)
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [X] Any dependent changes have been merged and published in downstream modules

2023-10-26 19:36 UTC, sqrrrl requested changes

2023-10-26 19:36 UTC, sqrrrl commented on advanced/chat.gs
> +    try {
Suggest moving the try outside the do...while loop.  As written, there's also a potential for an infinite loop as any unrecoverable error fetching a page would cause it to retry the same request repeatedly.

2023-10-26 19:36 UTC, sqrrrl commented on advanced/chat.gs
> +      for (let i = 0; i < response.memberships.length; i++) {
Prefer forEach()

```
response.memberships.forEach(member => console.log(....))
```

2023-10-26 19:36 UTC, sqrrrl commented on advanced/chat.gs
> +      if (!response.memberships || response.memberships.length === 0) {
Haven't looked at chat API specifically, but in general empty results in our APIs do not signal the end of the list. There are cases where data is filtered at the API level which can result in an empty page in the middle of a list.

Still want to check that there are values, but instead of returning, advance to the next page token and continue the loop:

```
if (!response.memberships || response.memberships.length === 0) {
  pageToken = response.nextPageToken;
  continue;
}
```

2023-10-26 20:35 UTC, gtondello commented on advanced/chat.gs
> +      if (!response.memberships || response.memberships.length === 0) {
Yes, good point, this can happen in Chat API. So, this is a welcome suggestion.

2023-10-27 13:58 UTC, gtondello requested changes

2023-10-27 13:58 UTC, gtondello commented on advanced/chat.gs
> +  }
```suggestion
  try {
    do {
      response = Chat.Spaces.Members.list(spaceName, {
        pageSize: 10,
        pageToken: pageToken
      });
      if (!response.memberships || response.memberships.length === 0) {
        pageToken = response.nextPageToken;
        continue;
      }
      response.memberships.forEach(member => console.log(
        'Member resource name: %s (type: %s)',
        membership.name,
        membership.member.type);
      pageToken = response.nextPageToken;
    } while (pageToken);
  } catch (err) {
    // TODO (developer) - Handle exception
    console.log('Failed with error %s', err.message);
  }
```

Missing the `do...while` loop inside the `try`.

2023-10-27 13:58 UTC, gtondello commented on advanced/chat.gs
> +    response.memberships.forEach(member => console.log(
```suggestion
    response.memberships.forEach(membership => console.log(
```

2023-10-27 17:47 UTC, sqrrrl approved these changes

2023-10-27 17:58 UTC, gtondello requested changes

2023-10-27 17:58 UTC, gtondello commented on advanced/chat.gs
> +        membership.member.type);
```suggestion
        membership.member.type));
```

2023-10-27 18:21 UTC, gtondello approved these changes

2023-10-27 18:41 UTC, merged