Add new sample that is for a Google Workspace Add-on that adds sentim…
googleworkspace/apps-script-samples pull request #496
Opened 2024-10-18 11:40 UTC by chanelgreco

…ent analysis capabilities to Gmail.

# Description

This is a new sample that creates a Google Workspace Add-ons that extends Gmail with sentiment analysis capabilities. 

Fixes # (issue)

## Is it been tested?
- [x] Development testing done

## Checklist

- [x ] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have performed a peer-reviewed with team member(s)
- [x ] I have commented my code, particularly in hard-to-understand areas
- [x ] I have made corresponding changes to the documentation
- [x ] My changes generate no new warnings
- [x ] Any dependent changes have been merged and published in downstream modules

2024-10-21 15:05 UTC, sqrrrl requested changes

2024-10-22 09:53 UTC, chanelgreco commented on gmail-sentiment-analysis/appsscript.json
> +            "onTriggerFunction": "onGmailMessage"
Checked the dev docs and I can delete the entire conextualTriggers object.

2024-10-22 09:53 UTC, chanelgreco commented on gmail-sentiment-analysis/Code.gs
> +  if(e.hostApp =="gmail"){
Will remove and change manifest file accordingly.

2024-10-22 10:47 UTC, chanelgreco commented on gmail-sentiment-analysis/Gmail.gs
> +  for (let i = 0 ; i < msgs.length; i++) {
My personal preference is the forEach method when looping over an array.
But the traditional for loop is significantly quicker. I've tested it and I think we should keep the code as is to make sure there aren't any timeouts.

2024-10-22 14:48 UTC, chanelgreco commented on gmail-sentiment-analysis/Gmail.gs
> +      if(regex.test(currentPrediction)){
Holy smokes, I spent hours on this line of code!
It seems as if there's a hidden character (maybe a new line?) because the simple check currendPrediction === "FALSE" always was false. So the label was never applied even if the response from Vertex AI was "FALSE".

2024-10-24 15:42 UTC, sqrrrl approved these changes

2024-10-24 16:23 UTC, merged